//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Air_Ticket = new HashSet<Air_Ticket>();
        }
    
        public int ID_Client { get; set; }
        public string Name { get; set; }
        public string SurName { get; set; }
        public string MidName { get; set; }
        public string Gender { get; set; }
        public string Passport_Ser { get; set; }
        public string Passport_Num { get; set; }
        public System.DateTime Date_Passport { get; set; }
        public string IntPassport_Ser { get; set; }
        public string IntPassport_Num { get; set; }
        public string Phone_Number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Air_Ticket> Air_Ticket { get; set; }
    }
}
