//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deleted_Reports
    {
        public int ID_DelReport { get; set; }
        public int Order_ID { get; set; }
        public System.DateTime Report_Date { get; set; }
        public System.DateTime DeletedTime { get; set; }
    }
}
