//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class FullOrder
    {
        public int ID_Order { get; set; }
        public string Company_Name { get; set; }
        public string Payment_Method { get; set; }
        public int Order_Cost { get; set; }
        public int Num_Trip { get; set; }
        public int Cost_Ticket { get; set; }
        public System.DateTime Dates { get; set; }
        public string Name { get; set; }
        public string SurName { get; set; }
        public string MidName { get; set; }
        public string Gender { get; set; }
        public string Passport_Ser { get; set; }
        public string Passport_Num { get; set; }
        public string IntPassport_Ser { get; set; }
        public string IntPassport_Num { get; set; }
        public System.DateTime Date_Passport { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public int Cost { get; set; }
        public string Hotel_Name { get; set; }
        public string Voucher_Num { get; set; }
        public string Phone_Number { get; set; }
    }
}
